version: "3"
services:
  review_webhook:
    build: ./webhook
    ports:
      - "3005:3000"
    depends_on:
      - redis

  review_worker:
    build: ./worker
    depends_on:
      - redis
      - ollama

  review_redis:
    image: redis:7

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: